### ISSUE TITLE
8M PBMC raw dataset

### ISSUE THREAD

**Issue by JWatter** [theislab/scPoli_reproduce#13]
Hi,

great effort and work!

We would like to make use of your 8M PBMC dataset as well and I wanted to ask if you could upload the "raw" dataset before filtering? The [pbmc_raw.h5ad.gz](https://figshare.com/articles/dataset/pbmc_raw_h5ad_gz/21688029) dataset only contains the 10k highly variable genes.
Furthermore, in .var there are no gene symbols only ensembl IDs. If the gene symbols stored somewhere as well, that would be highly appreciated!

Best,
Jan

**Comment by cdedonno** [comment]
Hi @JWatter, unfortunately, that's the "rawest" dataset I can provide, I have received the data internally and it was already filtered. As for gene symbols, you should be able to pull them using [Scanpy]( https://scanpy.readthedocs.io/en/stable/generated/scanpy.queries.biomart_annotations.html).

**Comment by JWatter** [comment]
Thanks for the scanpy function, was not aware of it!
... And I guess no chance you could trace back where you got the dataset from?

**Comment by cdedonno** [comment]
It was a collection of datasets put together for a CZI workshop, I think @soroorh might have more information. The datasets that were collected are cited in the manuscript.
