### ISSUE TITLE
Question about learned conditional embedding

### ISSUE THREAD

**Issue by aj088** [theislab/scPoli_reproduce#8]
Hi, I am confused about the input of conditional embedding. In the paper it said the embedding dimension is not one-hot-encoded, but comes with a fixed dimensionality. What should be the dimension of conditional embedding, would it be a matrix with E fixed dimensions by cells? And how do you define E dimensions? Thanks!

**Comment by cdedonno** [comment]
Hi, as stated in the paper, the conditional embeddings are initialized using `torch.nn.Embedding`. It is essentially a look-up matrix of dimensionality SxE (S: number of samples, E: embedding dimensionality). The dimensionality to use is an hyperparameter, it will depend on how many conditions you plan to integrate. Intuitively you want E to be smaller than S. In our work we found that 25-dimensional embeddings or so work well even in the case of thousands of samples.

I hope this clears your confusion.

**Comment by aj088** [comment]
Thanks for the quick response. If the conditional embedding matrix has dimensionality SxE, how can it be concatenated to the gene matrix of dimensionality GxC (G: #genes and C: # of cells)? And it seems that training an encoder from conditional embeddings and gene expression matrix gives a latent representation that still has batch effects. Can you explain a little more about how conditional embedding is trained and optimized through the CVAE model? Thanks!

**Comment by cdedonno** [comment]
We don't concatenate the full gene expression matrix and the conditional embedding matrix. Each cell has a condition/sample associated to it. Therefore to each gene expression vector that we provide as input to the model we concatenate the conditional embedding of the correspondent condition/sample. These embeddings are learnable and we backpropagate to them during training, which is how they are optimized.
